emails[emails$text==min(nchar(emails$text)),]
library(tm)
emailcorpus<-Corpus(VectorSource(emails$text))
corpus<-tm_map(emailcorpus,tolower)
corpus<-tm_map(corpus,PlainTextDocument)
corpus<-tm_map(corpus,removePunctuation)
corpus<-tm_map(corpus,removeWords,stopwords("english"))
corpus<-tm_map(corpus,stemDocument)
dtm<-DocumentTermMatrix(corpus)
spdtm<-removeSparseTerms(dtm,0.95)
emailsSparse<-as.data.frame(as.matrix(spdtm))
colnames(emailsSparse)<-make.names(colnames(emailsSparse))
which.max(colSums(emailsSparse))

e1<-subset(emailsSparse,emailsSparse$spam==1)
colnames(e1[,colSums(e1)>1000])
emailsSparse$spam<-emails$spam
----
  sort(colSums(subset(emailsSparse, spam == 0)))
---
library(caTools)
  set.seed(123)
spl<-sample.split(emailsSparse$spam,SplitRatio=0.7)
train<-subset(emailsSparse,spl==TRUE)
test<-subset(emailsSparse,spl==FALSE)
spamlog<-glm(spam~.,data=train,family="binomial")
logpred<-predict(spamlog,type="response")
testpred<-predict(spamlog,newdata=test,type="response")
table(test$spam,testpred>0.5)
ROCRpred<-prediction(testpred,test$spam)
as.numeric(performance(ROCRpred,"auc")@y.values)

library(rpart)
spamcart<-rpart(spam~.,data=train,method="class")
cartpred<-predict(spamcart)
table(train$spam,cartpred)
library(ROCR)
ROCRpred<-prediction(cartpred[,2],test$spam)
as.numeric(performance(ROCRpred,"auc")@y.values)
cartpred<-predict(spamcart,newdata=test)
table(test$spam,cartpred[,2]>0.5)


set.seed(123)
library(randomForest)
spamrf<-randomForest(as.factor(spam)~.,data=train)
rfpred<-predict(spamrf,type="prob")
table(train$spam,rfpred[,2]>0.5)
ROCRpred<-prediction(rfpred[,2],train$spam)
as.numeric(performance(ROCRpred,"auc")@y.values)
rfpred<-predict(spamrf,newdata=test,type="prob")
table(test$spam,rfpred[,2]>0.5)
ROCRpred<-prediction(rfpred[,2],test$spam)
as.numeric(performance(ROCRpred,"auc")@y.values)

